version: "3.7"

services:
  nginx:
    container_name: whoislocal-server
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/dev/nginx/Dockerfile
    environment:
      SERVER_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/dev/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN_NAME}
    volumes:
      - ./:/var/www/html

  php-cli:
    build:
      context: ./
      dockerfile: docker/dev/php-cli/Dockerfile
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8
    container_name: whoislocal-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"